-- orca.nvim is a local colorscheme — not managed by vim.pack.
-- To use a local plugin, add its directory to the runtimepath manually:
--   vim.opt.rtp:prepend("~/.source/orca.nvim")
--   require("orca").setup({ transparent_bg = true })
